##############################################################################
# IAvsHT — Statistical Validation of the Train / Validation Split
# ─────────────────────────────────────────────────────────────────────────────
# Performs a variable-by-variable statistical comparison between the Train and
# Val subsets to confirm that the split generated by IAvsHT_Creation_Split.py
# is statistically balanced. Three tests are applied depending on variable type:
#   · Continuous  (Age)     → Welch's t-test
#   · Ordinal               → Mann-Whitney U
#   · Binary (all others)   → Pearson's Chi-squared
#
# Criterion: p > 0.05 → no significant difference → variable is balanced.
# Output: results exported to a new 'Validacion_Split' sheet in the Excel file.
# Input:  IAvsHT_VALLADOLID_2023.xlsx (must contain 'Train' and 'Val' sheets)
##############################################################################

import pandas as pd
import numpy as np
from scipy.stats import ttest_ind, chi2_contingency, mannwhitneyu

# ── Data loading ──────────────────────────────────────────────────────────────

EXCEL_FILE = 'IAvsHT_VALLADOLID_2023.xlsx'

df_train = pd.read_excel(EXCEL_FILE, sheet_name='Train')
df_val   = pd.read_excel(EXCEL_FILE, sheet_name='Val')

# Remove target and HT decision columns — not clinical variables
for df in [df_train, df_val]:
    df.drop(columns=[df.columns[-1], 'OBJETIVO HT'], inplace=True, errors='ignore')

print(f"Train: {len(df_train)} patients | Val: {len(df_val)} patients | "
      f"Variables analysed: {len(df_train.columns)}")

# ── Variable-by-variable statistical comparison ───────────────────────────────

results = []

for col in df_train.columns:
    tr = df_train[col].dropna()
    va = df_val[col].dropna()

    if col == 'EDAD':
        # Continuous variable — Welch's t-test (does not assume equal variances)
        _, p   = ttest_ind(tr, va, equal_var=False)
        test   = "Welch's t-test"
        desc_tr = f"{tr.mean():.1f} ± {tr.std():.1f}"
        desc_va = f"{va.mean():.1f} ± {va.std():.1f}"

    elif tr.nunique() <= 2:
        # Binary variable — Pearson's Chi-squared
        table = pd.crosstab(
            pd.Series(np.append(tr.values, va.values)),
            pd.Series(['Train'] * len(tr) + ['Val'] * len(va))
        )
        _, p, _, _ = chi2_contingency(table) if table.shape == (2, 2) else (None, 1.0, None, None)
        test    = 'Chi-squared'
        desc_tr = f"{tr.mean():.3f}  ({int(tr.sum())}/{len(tr)})"
        desc_va = f"{va.mean():.3f}  ({int(va.sum())}/{len(va)})"

    else:
        # Ordinal variable — Mann-Whitney U (non-parametric)
        _, p   = mannwhitneyu(tr, va, alternative='two-sided')
        test   = 'Mann-Whitney U'
        desc_tr = f"{tr.mean():.2f} ± {tr.std():.2f}"
        desc_va = f"{va.mean():.2f} ± {va.std():.2f}"

    results.append({
        'Variable':              col,
        'Statistical test':      test,
        f'Train (n={len(df_train)})': desc_tr,
        f'Val (n={len(df_val)})':     desc_va,
        'p-value':               round(p, 4),
        'Balanced':              'Yes' if p >= 0.05 else 'No',
    })

# ── Summary ───────────────────────────────────────────────────────────────────

df_result = pd.DataFrame(results).sort_values('p-value').reset_index(drop=True)

n_ok  = (df_result['Balanced'] == 'Yes').sum()
n_nok = len(df_result) - n_ok

print(f"\nBalanced variables (p > 0.05):     {n_ok}/{len(df_result)}")
print(f"Unbalanced variables (p ≤ 0.05):   {n_nok}/{len(df_result)}")

if n_nok == 0:
    print("\nValid split: no variable shows a statistically significant imbalance.")
else:
    print("\nVariables with potential imbalance:")
    print(df_result[df_result['Balanced'] == 'No'].to_string(index=False))

# ── Export results ────────────────────────────────────────────────────────────
# Written to a new sheet without altering the Train or Val sheets.

with pd.ExcelWriter(EXCEL_FILE, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df_result.to_excel(writer, sheet_name='Validation_Split', index=False)

print(f"\nResults saved to sheet 'Validation_Split' in {EXCEL_FILE}.")
